name: Deploy to GitHub pages

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0
      - run: dotnet build --configuration Release
      - run: dotnet publish naeem.csproj -c Release -o release –nologo
      - run: sed -i ‘s/<base href=”\/” \/>/<base href=”\/naeem\/” \/>/g’ release/wwwroot/index.html
      - run: cp release/wwwroot/index.html release/wwwroot/404.html
      - run: touch release/wwwroot/.nojekyll
      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot
          
      
